-- Sillage by RLN Consulting — Migration 0007 : catégories détaillées de
-- revenus et charges, reprises du tableau budgétaire du réseau CGP de
-- l'utilisatrice (structure en 10 groupes de charges + 6 groupes de
-- revenus). Les anciennes valeurs génériques restent acceptées pour ne
-- jamais invalider des données déjà saisies.

alter table revenus drop constraint revenus_type_check;
alter table revenus add constraint revenus_type_check
  check (type in (
    'salaire_conjoint1',
    'salaire_conjoint2',
    'bonus_conjoint1',
    'bonus_conjoint2',
    'bic_bnc_conjoint1',
    'bic_bnc_conjoint2',
    'benefices_agricoles_conjoint1',
    'benefices_agricoles_conjoint2',
    'revenus_gerant_conjoint1',
    'revenus_gerant_conjoint2',
    'prestations_sociales',
    'allocation_chomage_conjoint1',
    'allocation_chomage_conjoint2',
    'pension_retraite_conjoint1',
    'pension_retraite_conjoint2',
    'pension_alimentaire_recue',
    'rente_viagere',
    'revenus_fonciers_conjoint1',
    'revenus_fonciers_conjoint2',
    'caf_secu_conjoint1',
    'caf_secu_conjoint2',
    'autres_aides',
    'autre_revenu',
    'salaire',
    'revenus_professionnels',
    'revenus_fonciers',
    'pensions',
    'retraites',
    'dividendes',
    'interets',
    'autres'
  ));

alter table charges drop constraint charges_type_check;
alter table charges add constraint charges_type_check
  check (type in (
    'impot_revenu_ifi',
    'urssaf_emploi_domicile',
    'cotisations_independant',
    'loyer_ou_pret_principal',
    'taxes_foncieres_habitation',
    'assurance_pret',
    'charges_copropriete',
    'ameublement_electromenager',
    'energies',
    'telephone_internet',
    'residence_secondaire_entretien',
    'bricolage_travaux',
    'assurance_habitation_scolaire',
    'alimentation',
    'vetements',
    'depenses_fetes',
    'beaute_coiffeur',
    'soins_non_rembourses',
    'assurance_sante',
    'autres_courses',
    'employe_domicile',
    'depenses_pro_microentrepreneur',
    'frais_scolaires',
    'frais_garde',
    'transport_enfants',
    'pension_alimentaire_versee',
    'activites_enfants',
    'nourriture_garde_animaux',
    'soins_veterinaires',
    'abonnement_transport_commun',
    'entretien_vehicule',
    'assurance_auto_moto',
    'carburant',
    'peage_abonnement',
    'prets_divers',
    'assurance_prevoyance',
    'frais_bancaires',
    'pret_immobilier_locatif',
    'assurance_pret_locatif',
    'assurance_pno',
    'charges_copro_locatif',
    'travaux_immo_locatif',
    'activites_loisirs',
    'sorties_culturelles',
    'presse_livres',
    'restaurants',
    'tabac_jeux',
    'vacances',
    'sorties_amis',
    'abonnements_loisirs',
    'dons',
    'cadeaux',
    'autre_charge',
    'credit_immobilier',
    'credit_consommation',
    'leasing',
    'loyer',
    'pension_versee',
    'charges_recurrentes',
    'autres'
  ));
